### ISSUE TITLE
getPk() returning exponential notation

### ISSUE THREAD

**Issue by GitDov** [liamcottle/Instagram-SDK-PHP#3]
@liamcottle  First congratulations for the SDK, great work.

Some Pk and media_ids are returning values in exponential notation like the example:
$pk = $timelineFeedItem->getPk();

PK: 1.2616070641251E+18

Do you know how can i solve that?

**Comment by liamcottle** [comment]
This happens if you are running PHP on a 32 bit system.

If you're just echoing the value, you should be able to fix it with the `number_format` method.

I have only used and tested this library on 64 Bit systems, so am unsure if this causes any issues with the other methods that take the PK value and send it to the API.

**Comment by GitDov** [comment]
I put it in a webserver and it worked.
Thanks a lot.
